### ISSUE TITLE
Options prop doesn't work

### ISSUE THREAD

**Issue by DimaBur** [SamyPesse/react-mathjax#20]
I tried to set custom options like 
```
tex2jax: {
    inlineMath: [['$','$'], ['\\(','\\)']],
    processEscapes: true
  }
```
but nothing happened.
I tried to change `DEFAULT_OPTIONS` inside component, but nothing happened too. Then I completely removed ```const { options } = this.props;
        MathJax.Hub.Config(options);``` and it had no impact on the component.

**Comment by frederikcreemers** [comment]
This makes sense, because according to [the docs on loading and configuring MathJax](http://docs.mathjax.org/en/latest/configuration.html#using-in-line-configuration-options), it expects a configuration script to be present before it loads:

> Because MathJax starts its configuration process as soon as it is loaded, the configuration script must come **before** the script tag that loads MathJax.js itself. You do this by including a <script> with type="text/x-mathjax-config" whose content will be run when MathJax performs its configuration.

You can also [do it in plain JavaScript](http://docs.mathjax.org/en/latest/configuration.html#using-plain-javascript) by setting a global variable. This might be the easiest route to take here. We just set this inside the Provider's constructor before MathJax is ever loaded.

```html
<script type="text/javascript">
  window.MathJax = {
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      processEscapes: true
    }
  };
</script>
<script type="text/javascript" src="path-to-MathJax/MathJax.js?config=TeX-AMS_HTML">
</script>
```

**Comment by DimaBur** [comment]
Thank you, I've already solved this problem in this way.
